### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by jardakotesovec** [hapijs/catbox-mongodb#25]
Unfortunately I don't have use case for using mongoDB anymore, so I have not been using actively this module for some time. 

Therefore I believe that it would be better to pass maintainer position to someone, who uses this module in production and is more aware whats going on in MongoDB world.

Great candidate would be someone who already made some contribution to this module or some other catbox adapter.

All info about maintaining hapi modules is concentrated here: https://github.com/hapijs/contrib

**Comment by marcuspoehls** [comment]
Hey Jarda, I submitted PR https://github.com/hapijs/catbox-mongodb/pull/28 to support catbox 10 with catbox-mongo.

I'm interested in maintaining this module, if you're still looking for a new maintainer :)

**Comment by jardakotesovec** [comment]
Hey, that would be great. I will look more into your PR during the weekend and we will go from there.

**Comment by marcuspoehls** [comment]
Awesome, thanks!

**Comment by jardakotesovec** [comment]
@hueniverse Hi, can you give @marcuspoehls github access? AFAIK only organisation owners can do that.

**Comment by hueniverse** [comment]
@marcuspoehls you are all set on GitHub and npm.

**Comment by jardakotesovec** [comment]
@marcuspoehls All yours :-).

**Comment by marcuspoehls** [comment]
@jardakotesovec @hueniverse Thank you 😊

**Comment by Marsup** [comment]
Thanks for your past investment in it @jardakotesovec ! And welcome to you @marcuspoehls !

**Comment by marcuspoehls** [comment]
@Marsup Thank you!
