### ISSUE TITLE
Re-use existing connection / collection.

### ISSUE THREAD

**Issue by j** [hapijs/catbox-mongodb#31]
It would be nice to not have to re-connect to MongoDB to use this if I'm already connected elsewhere.

**Comment by marcuspoehls** [comment]
@j Hi Jordan,

do you mean re-using a connection outside of `catbox-mongodb`?

Like, you’re connecting to MongoDB when starting your app and you want catbox to re-use this existing connection?

Doesn‘t that mean `catbox-mongodb` would use the same database as the existing connection?

**Comment by marcuspoehls** [comment]
@j Hey Jordan,

can you please share more details on what you'd expect `catbox-mongodb` to solve?
Thanks :)

**Comment by marcuspoehls** [comment]
@j Hey Jordan,

I’ll close this issue here. Let me know if you still see the urge to tackle this and how you’d approach it. 
Thank you :)
